#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_FOCAL) += focal_common.o
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT3518) += ft3518/
#endif
