#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

snd-audio-extend-objs := audio_extend_drv.o
obj-y += snd-audio-extend.o
snd-hal-feedback-objs := hal_feedback.o
obj-$(CONFIG_OPLUS_FEATURE_MM_FEEDBACK) += snd-hal-feedback.o
