# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

obj-$(CONFIG_OPLUS_FEATURE_DNS_HOOK) += oplus_dns_hook/

obj-$(CONFIG_OPLUS_FEATURE_STATS_CALC) += oplus_stats_calc/

obj-$(CONFIG_OPLUS_FEATURE_QR_SCAN) += oplus_qr_scan/

