#obj-$(CONFIG_OPLUS_COMMON_SOFT)  +=  oplus_project/


#obj-$(CONFIG_OPLUS_HYPNUS)       +=  oplus_hypnus/

#obj-$(CONFIG_OPLUS_SHUTDOWN_DETECT)  +=  oplus_shutdown_detect/
#obj-$(CONFIG_OPLUS_CRITICALLOG)  +=  oplus_criticallog/
obj-y  +=  oplus_criticallog/

#obj-$(CONFIG_OPLUS_PHOENIX)     +=  oplus_phoenix/

#obj-$(CONFIG_OPLUS_KEY_HANDLE)    +=  oplus_key_handle/

