#obj-$(CONFIG_OPLUS_CRITICALLOG)	+=  oplus_criticallog.o
#Xiaoshan.Huang
#obj-$(CONFIG_OPLUS_CRITICALLOG)   +=  oplus_criticallog.o

#obj-$(CONFIG_OPLUS_CRITICALLOG)   +=  oplus_criticallog.o
obj-y  +=  oplus_criticallog.o criticallog_class.o
